apiVersion: v1
kind: Service
metadata:
  name: telediscobot-svc
  labels:
    app: telediscobot
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: telediscobot
  type: ClusterIP